version: "3"

services:
  cursos_catedu:
    build: .
    restart: always
    container_name: cursos-catedu
    command: "gunicorn --workers=1 --threads=1 -b 0.0.0.0:8050 app:server"
    volumes:
      - .:/home/app
    expose:
      - "8050"
    environment:
      VIRTUAL_HOST: "mapeocdd.catedu.es"
      LETSENCRYPT_HOST: "mapeocdd.catedu.es"
      LETSENCRYPT_EMAIL: "jesuslopezdeleyva@gmail.com"
      APPUSER: ${APPUSER}
      PASSWORD: ${PASSWORD}
    networks:
      - nginx-proxy_frontend

networks:
  nginx-proxy_frontend:
    external: true
